"""
concatenate_outputs.py

Purpose:
This script is designed to concatenate multiple CSV files generated by the webinar-report-merge.py script.
It is intended to be used after processing multiple webinar reports, combining their outputs into a single CSV file.

Key features:
- Concatenates all CSV files in the specified output directory
- Preserves the header from the first file
- Sorts files alphabetically before concatenation
- Provides console output for successful concatenation or if no CSV files are found
- Assumes all CSV files in the output directory have the same structure

Usage:
Place this script in the same directory as webinar-report-merge.py and run it after processing multiple webinar reports.
The output directory and filename can be modified by changing the default parameters in the concatenate_csv_files function.
"""

import os
import pandas as pd
import glob

def concatenate_csv_files(output_dir='output', output_filename='concatenated_webinar_data.csv'):
    """
    Concatenate all CSV files in the specified output directory into a single CSV file.

    Args:
    output_dir (str): The directory containing the CSV files to concatenate. Default is 'output'.
    output_filename (str): The name of the output file. Default is 'concatenated_output.csv'.

    Returns:
    None
    """
    # Get all CSV files in the output directory, sorted alphabetically
    csv_files = sorted(glob.glob(os.path.join(output_dir, '*.csv')))
    
    # Check if any CSV files were found
    if not csv_files:
        print(f"No CSV files found in the '{output_dir}' directory.")
        return
    
    # Initialize an empty list to store individual DataFrames
    df_list = []

    # Read each CSV file and append it to the list
    for file in csv_files:
        df = pd.read_csv(file)
        df_list.append(df)
    
    # Concatenate all DataFrames in the list
    # ignore_index=True resets the index to avoid duplicate indices
    concatenated_df = pd.concat(df_list, ignore_index=True)
    
    # Determine the full path for the output file
    output_path = os.path.join(os.getcwd(), output_filename)

    # Save the concatenated DataFrame to a new CSV file
    # index=False prevents writing row indices to the CSV
    concatenated_df.to_csv(output_path, index=False)
    
    # Print success message
    print(f"Successfully concatenated {len(csv_files)} CSV files.")
    print(f"Output saved to: {output_path}")

if __name__ == "__main__":
    # Execute the concatenation function when the script is run directly
    concatenate_csv_files()
